DROP TABLE IF EXISTS
 TCM_SAMPLE
 CASCADE
;
CREATE TABLE TCM_SAMPLE (
  TCM_SAMPLE_ID IDENTITY PRIMARY KEY,
  SAMPLE_NAME VARCHAR(50)
)
;
--CREATE SEQUENCE SCM_SAMPLE_ID START WITH 1 INCREMENT BY 1 MAXVALUE 999999999999 NOCYCLE NOCACHE

